### ISSUE TITLE
怎么验证客户端证书吊销

### ISSUE THREAD

**Issue by zhujintao** [nareix/tls-example#1]
已经生成了CRL文件，但不知如何使用

**Comment by livelyRyan** [comment]
弄一个CRL的服务器，客户端从server的证书里面找分发点，然后去CRL服务器下载，然后解析CR文件

**Comment by zhujintao** [comment]
好的,谢谢! 
如果服务端主动拒绝失效的客户端连接的话是要在服务端做解析CR吗?
